name = "RPGPack"
author = "firstlane"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "66d1a35ebd43a5b81fa2a9211a7ab30ae1789f2182438497ade7d22274d92f92"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
